[book]
authors = ["Patrick Jackson"]
title = "Eidetica Documentation"
language = "en"

[output.html]
default-theme = "light"
additional-js = ["mermaid-init.js"]
git-repository-url = "https://github.com/arcuru/eidetica"
